"""add nutrition_tables and table_versions

Revision ID: 4c19d1df5285
Revises: 20a84d79f8d0
Create Date: 2026-02-24 15:21:36.212837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c19d1df5285'
down_revision = '20a84d79f8d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('product_data', sa.JSON(), nullable=False),
    sa.Column('ingredients_data', sa.JSON(), nullable=False),
    sa.Column('result_data', sa.JSON(), nullable=False),
    sa.Column('ingredient_count', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_finalized', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('nutrition_tables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nutrition_tables_user_id'), ['user_id'], unique=False)

    op.create_table('table_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('product_data', sa.JSON(), nullable=False),
    sa.Column('ingredients_data', sa.JSON(), nullable=False),
    sa.Column('result_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['nutrition_tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('table_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_table_versions_table_id'), ['table_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_table_versions_table_id'))

    op.drop_table('table_versions')
    with op.batch_alter_table('nutrition_tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nutrition_tables_user_id'))

    op.drop_table('nutrition_tables')
    # ### end Alembic commands ###
